server:
  port: 8080
  servlet:
    context-path: /mybatis

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml
  # datasource
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis
    username: root
    password: guojian

    spring:
      freemarker:
        template-loader-path: templates/*.ftl #模板加载路径 按需配置
        request-context-attribute: req  #req访问request
        suffix: .ftl  #后缀名
        content-type: text/html
        enabled: true
        cache: false #缓存配置
        charset: UTF-8 #编码格式
        settings:
          number_format: '0.##'   #数字格式化，无小数点




