server:
  port: 8080
  servlet:
    context-path: /mybatis
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml
  type-aliases-package:a
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis
    username: root
    password: guojian
      #  freemarker
  freemarker:
    template-loader-path: templates/**
  mvc:
    static-path-pattern: static/**



